version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: automate-whatsapp
        container_name: automate-whatsapp
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: /entrypoint.sh

    db:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: automate
            MYSQL_ROOT_PASSWORD: OneLove2013@
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
